name: Deno CI

on: push

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check
      - run: deno lint
      - run: deno test --allow-all --coverage=cov/
      - run: deno coverage --lcov cov/ > cov.lcov
