name: GitHub Action for Deno
  # uses: denolib/deno-action@3dba16f4c69fc2de21d9e9792b70923a982fe273

on:
  pull_request:
    branches: [ master, main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/deno-action@0.19.0
      - run: deno run -A src/main.ts
      - run: deno test -A src/main.ts
      - run: npm compile -A src/main.ts
          
